openapi: 3.0.0
info: 
  title: learn express and swagger  - LearCodeOnline
  description: LCO - a course segment about writing docs
  version: 1.1.0
  contact: 
    email: atharvamahamuni@outlook.com
    url: "http://localhost:4000/"

servers: 
  - url: "{protocol}://localhost:4000/api/{version}"
    description: for local host
    variables:
      version:
        enum:
          - v1
          - v2
      protocol:
        enum:
          - http
          - https
        

