openapi: 3.0.0
info:
  title: Social App
  description: Our first Social App at LCO - Atharva
  version: 1.0.1

servers:
  - url: http://localhost:4000/api/v1
    description: Localhost version of our application.
  - url: https://localhost:4000/api/v1
    description: This is just a dummy API url it doesn't work

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    BearerAuth:
      type: http
      scheme: bearer

paths:
  /instagram:
    get:
      summary: returns username, followers, follows and current date-time
      responses:
        '200': # Status code
          description: returns an object
          content: 
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                  followers:
                    type: integer
                  follows:
                    type: integer
  /{token}:
    get:
      summary: returns whatever there in parameters
      parameters:
        - name: token
          default: 5
          in: path
          schema:
            type: string

      responses:
        '200': # Status code
          description: returns an object which we pass to it
          content: 
            application/json:
              schema:
                type: object
                properties:
                  params:
                    type: string
                  


  