openapi: 3.0.0
info: 
  title: Ecommerce store
  description: course segment about Ecom store
  version: 1.1.0
  contact: 
    email: atharvamahamuni@outlook.com
    url: "http://localhost:4000/"

servers: 
  - url: "{protocol}://localhost:4000/api/{version}"
    description: for local host
    variables:
      version:
        enum:
          - v1
          - v2
        default: v1
      protocol:
        enum:
          - http
          - https
        default: http
        
components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: token
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
paths:
  /dummy:
    get:
      tags:
        - string
      summary: returns a greet message from LCO
      responses: 
        200:
          description: All good and success
        400:
          description: Bad request
        500:
          description: Internal server error